import { withTenantPostgresTransaction } from "@monpiole/persistence";
import { and, desc, eq, lt, or } from "drizzle-orm";
import type { Pool } from "pg";
import type { PropertyInquiryCursor, PropertyInquiryPage, PropertyInquiryRepository } from "../../../application/property-inquiry-repository.js";
import { PropertyInquiry, type PropertyInquiryStatus } from "../../../domain/property-inquiry.js";
import { properties, propertyInquiries } from "./schema.js";

export class PostgresPropertyInquiryRepository implements PropertyInquiryRepository {
  constructor(private readonly pool:Pool){}
  submitForPublishedProperty(inquiry:PropertyInquiry,publicPropertyId:string,trace:{correlationId:string;actorId:string}):Promise<PropertyInquiry|undefined>{return withTenantPostgresTransaction(this.pool,inquiry.values.tenantId,async(scope)=>{
    const property=(await scope.database().select({id:properties.propertyId}).from(properties).where(and(eq(properties.tenantId,inquiry.values.tenantId),eq(properties.propertyId,publicPropertyId),eq(properties.status,"PUBLISHED"))).limit(1).for("update"))[0];if(!property)return undefined;
    const existing=(await scope.database().select().from(propertyInquiries).where(and(eq(propertyInquiries.tenantId,inquiry.values.tenantId),eq(propertyInquiries.propertyId,property.id),eq(propertyInquiries.idempotencyKey,inquiry.values.idempotencyKey))).limit(1))[0];if(existing)return fromRow(existing);
    await scope.database().insert(propertyInquiries).values({...toRow(inquiry),correlationId:trace.correlationId,actorId:trace.actorId});return inquiry;});}
  list(tenantId:string,propertyId:string,limit:number,cursor?:PropertyInquiryCursor,status?:PropertyInquiryStatus):Promise<PropertyInquiryPage|undefined>{return withTenantPostgresTransaction(this.pool,tenantId,async(scope)=>{const exists=(await scope.database().select({id:properties.propertyId}).from(properties).where(and(eq(properties.tenantId,tenantId),eq(properties.propertyId,propertyId))).limit(1))[0];if(!exists)return undefined;const cursorFilter=cursor===undefined?undefined:or(lt(propertyInquiries.createdAt,cursor.createdAt),and(eq(propertyInquiries.createdAt,cursor.createdAt),lt(propertyInquiries.inquiryId,cursor.inquiryId)));const rows=await scope.database().select().from(propertyInquiries).where(and(eq(propertyInquiries.tenantId,tenantId),eq(propertyInquiries.propertyId,propertyId),status===undefined?undefined:eq(propertyInquiries.status,status),cursorFilter)).orderBy(desc(propertyInquiries.createdAt),desc(propertyInquiries.inquiryId)).limit(limit+1);const items=rows.slice(0,limit).map(fromRow);const last=rows.length>limit?items.at(-1):undefined;return{items,...(last?{nextCursor:{createdAt:last.values.createdAt,inquiryId:last.values.inquiryId}}:{})};});}
  find(tenantId:string,propertyId:string,inquiryId:string):Promise<PropertyInquiry|undefined>{return withTenantPostgresTransaction(this.pool,tenantId,async(scope)=>{const row=(await scope.database().select().from(propertyInquiries).where(and(eq(propertyInquiries.tenantId,tenantId),eq(propertyInquiries.propertyId,propertyId),eq(propertyInquiries.inquiryId,inquiryId))).limit(1))[0];return row?fromRow(row):undefined;});}
  update(tenantId:string,propertyId:string,inquiryId:string,change:(i:PropertyInquiry)=>PropertyInquiry,trace:{correlationId:string;actorId:string}):Promise<PropertyInquiry|undefined>{return withTenantPostgresTransaction(this.pool,tenantId,async(scope)=>{const row=(await scope.database().select().from(propertyInquiries).where(and(eq(propertyInquiries.tenantId,tenantId),eq(propertyInquiries.propertyId,propertyId),eq(propertyInquiries.inquiryId,inquiryId))).limit(1).for("update"))[0];if(!row)return undefined;const changed=change(fromRow(row));await scope.database().update(propertyInquiries).set({...toRow(changed),correlationId:trace.correlationId,actorId:trace.actorId}).where(and(eq(propertyInquiries.tenantId,tenantId),eq(propertyInquiries.inquiryId,inquiryId)));return changed;});}
}
type Row=typeof propertyInquiries.$inferSelect;
function fromRow(r:Row):PropertyInquiry{return PropertyInquiry.rehydrate({inquiryId:r.inquiryId,tenantId:r.tenantId,propertyId:r.propertyId,contactName:r.contactName,...(r.email?{email:r.email}:{}),...(r.phoneNumber?{phoneNumber:r.phoneNumber}:{}),...(r.message?{message:r.message}:{}),intent:r.intent as PropertyInquiry["values"]["intent"],...(r.preferredContactChannel?{preferredContactChannel:r.preferredContactChannel as PropertyInquiry["values"]["preferredContactChannel"]}:{}),consentVersion:r.consentVersion,consentGivenAt:instant(r.consentGivenAt),idempotencyKey:r.idempotencyKey,status:r.status as PropertyInquiryStatus,createdAt:instant(r.createdAt),updatedAt:instant(r.updatedAt),...(r.acknowledgedAt?{acknowledgedAt:instant(r.acknowledgedAt)}:{}),...(r.closedAt?{closedAt:instant(r.closedAt)}:{})});}
function toRow(i:PropertyInquiry){const v=i.values;return{inquiryId:v.inquiryId,tenantId:v.tenantId,propertyId:v.propertyId,contactName:v.contactName,email:v.email??null,phoneNumber:v.phoneNumber??null,message:v.message??null,intent:v.intent,preferredContactChannel:v.preferredContactChannel??null,consentVersion:v.consentVersion,consentGivenAt:v.consentGivenAt,idempotencyKey:v.idempotencyKey,status:v.status,createdAt:v.createdAt,updatedAt:v.updatedAt,acknowledgedAt:v.acknowledgedAt??null,closedAt:v.closedAt??null};}
function instant(value:string):string{return new Date(value).toISOString();}
