import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import { describe, expect, it, vi } from "vitest";
import { ApiForbiddenError, ApiSessionExpiredError } from "../../infrastructure/http/api-client.js";
import { ApiProblem } from "../../infrastructure/http/problem-details.js";
import type { PropertyApi } from "./property-api.js";
import { PropertyCompositionSection } from "./PropertyCompositionSection.js";
import type { Property, PropertyBuilding, PropertyUnit } from "./property-model.js";
const PROPERTY = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"; const BUILDING = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"; const BUILDING_B = "cccccccc-cccc-4ccc-8ccc-cccccccccccc"; const UNIT_A = "dddddddd-dddd-4ddd-8ddd-dddddddddddd"; const UNIT_B = "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee"; const NOW = "2026-08-28T12:00:00.000Z";
const property: Property = { propertyId: PROPERTY, title: "Résidence Lagune", propertyType: "HOUSE", transactionType: "SALE", status: "DRAFT", canWithdrawFromCatalog: false, structuralRole: "COMPOSITE", location: { country: "CI", city: "Abidjan", district: "Cocody", addressLine: "Rue 1" }, createdAt: NOW, updatedAt: NOW };
const building: PropertyBuilding = { buildingId: BUILDING, propertyId: PROPERTY, buildingCode: "BAT-A", name: "Immeuble A", createdAt: NOW, updatedAt: NOW };
function unit(id: string, code: string): PropertyUnit { return { unitCode: code, property: { ...property, propertyId: id, title: `Appartement ${code}`, structuralRole: "UNIT", propertyType: "APARTMENT", transactionType: "LONG_TERM_RENTAL" } }; }
function fakeApi(): PropertyApi { return { listProperties: vi.fn(), createProperty: vi.fn(), retrieveProperty: vi.fn(), updatePropertyDetails: vi.fn(), updatePropertyCoreInformation: vi.fn(), publishProperty: vi.fn(), withdrawPropertyFromCatalog: vi.fn(), retrievePropertyGeolocation: vi.fn(), updatePropertyGeolocation: vi.fn(), removePropertyGeolocation: vi.fn(), retrievePropertyAvailability: vi.fn().mockImplementation(async (propertyId: string) => ({ propertyId, source: "DIRECT", structuralRole: "UNIT", configured: false, canUpdateAvailability: true })), updatePropertyAvailability: vi.fn(), listPropertyPhotos: vi.fn(), registerPropertyPhoto: vi.fn(), retrievePropertyPhotoContent: vi.fn(), selectPropertyPrimaryPhoto: vi.fn(), deletePropertyPhoto: vi.fn(), retrievePropertyPhotoStandard: vi.fn(), updatePropertyPhotoStandard: vi.fn(), retrieveOwnerships: vi.fn(), retrievePropertyOwner: vi.fn(), listPropertyOwners: vi.fn(), createPropertyOwner: vi.fn(), updatePropertyOwner: vi.fn(), assignPropertyOwner: vi.fn(), removePropertyOwner: vi.fn(), listBuildings: vi.fn().mockResolvedValue({ items: [building], pageInfo: { nextCursor: null, hasNextPage: false } }), createBuilding: vi.fn().mockResolvedValue({ ...building, buildingId: BUILDING_B, buildingCode: "BAT-B", name: "Immeuble B" }), updateBuilding: vi.fn().mockResolvedValue({ ...building, buildingCode: "BAT-Z", name: "Immeuble Z" }), listUnits: vi.fn().mockResolvedValue({ items: [unit(UNIT_A, "A-101")], pageInfo: { nextCursor: null, hasNextPage: false } }), createUnit: vi.fn().mockResolvedValue(unit(UNIT_A, "A-101")), updateUnitCode: vi.fn().mockResolvedValue(unit(UNIT_A, "A-110")) }; }
function show(client: PropertyApi, current: Property = property, onStructuralRoleChange?: (role: Property["structuralRole"]) => void) { return render(<MemoryRouter><PropertyCompositionSection property={current} api={client} onStructuralRoleChange={onStructuralRoleChange} /></MemoryRouter>); }
describe("Composition du bien Web", () => {
  it("crée et modifie un Building avec des contraintes françaises", async () => { const client = fakeApi(); show(client); const edit = await screen.findByRole("group", { name: "Modifier Immeuble A" }); const newCode = screen.getByLabelText("Code du nouvel immeuble"); expect(newCode).toHaveAttribute("pattern"); expect(newCode).toHaveAttribute("title", expect.stringContaining("lettres")); fireEvent.change(newCode, { target: { value: "bat-b" } }); fireEvent.change(screen.getByLabelText("Nom du nouvel immeuble"), { target: { value: "Immeuble B" } }); fireEvent.click(screen.getByRole("button", { name: "Ajouter l’immeuble" })); await screen.findByText(/Immeuble ajouté avec succès/); expect(client.createBuilding).toHaveBeenCalledWith(PROPERTY, { buildingCode: "bat-b", name: "Immeuble B" }); fireEvent.change(within(edit).getByLabelText("Code de Immeuble A"), { target: { value: "BAT-Z" } }); fireEvent.change(within(edit).getByLabelText("Nom de l’immeuble"), { target: { value: "Immeuble Z" } }); fireEvent.click(within(edit).getByRole("button", { name: "Enregistrer l’immeuble" })); await screen.findByText("Immeuble modifié avec succès."); expect(client.updateBuilding).toHaveBeenCalledWith(PROPERTY, BUILDING, { buildingCode: "BAT-Z", name: "Immeuble Z" }); });
  it("consulte, modifie et pagine les Units avec un curseur opaque", async () => { const client = fakeApi(); vi.mocked(client.listUnits).mockResolvedValueOnce({ items: [unit(UNIT_A, "A-101")], pageInfo: { nextCursor: "opaque.cursor", hasNextPage: true } }).mockResolvedValueOnce({ items: [unit(UNIT_A, "A-101"), unit(UNIT_B, "A-102")], pageInfo: { nextCursor: null, hasNextPage: false } }); show(client); await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(screen.getByRole("button", { name: "Afficher les unités" })); const unitEdit = await screen.findByRole("group", { name: "Modifier le code de Appartement A-101" }); fireEvent.click(screen.getByRole("button", { name: "Afficher plus d’unités" })); await screen.findByRole("group", { name: "Modifier le code de Appartement A-102" }); expect(client.listUnits).toHaveBeenLastCalledWith(PROPERTY, BUILDING, "opaque.cursor"); expect(screen.getAllByRole("group", { name: "Modifier le code de Appartement A-101" })).toHaveLength(1); fireEvent.change(within(unitEdit).getByLabelText("Code de Appartement A-101"), { target: { value: "A-110" } }); fireEvent.click(within(unitEdit).getByRole("button", { name: "Enregistrer le code" })); await screen.findByText("Code de l’unité modifié avec succès."); expect(client.updateUnitCode).toHaveBeenCalledWith(PROPERTY, BUILDING, UNIT_A, "A-110"); });
  it("crée une Unit avec une description et une localisation préremplie mais modifiable", async () => { const client = fakeApi(); show(client); await screen.findByRole("group", { name: "Modifier Immeuble A" }); expect(screen.getByLabelText("Ville de l’unité")).toHaveValue("Abidjan"); expect(screen.getByLabelText("Adresse de l’unité")).toHaveValue("Rue 1"); fireEvent.change(screen.getByLabelText("Code de la nouvelle unité"), { target: { value: "A-102" } }); fireEvent.change(screen.getByLabelText("Titre de l’unité"), { target: { value: "Appartement A-102" } }); fireEvent.change(screen.getByLabelText("Description de l’unité"), { target: { value: "Deuxième étage" } }); fireEvent.change(screen.getByLabelText("Quartier de l’unité"), { target: { value: "Marcory" } }); fireEvent.change(screen.getByLabelText("Adresse de l’unité"), { target: { value: "Zone 4, A-102" } }); fireEvent.click(screen.getByRole("button", { name: "Ajouter l’unité" })); await screen.findByText("Unité ajoutée avec succès."); expect(client.createUnit).toHaveBeenCalledWith(PROPERTY, BUILDING, expect.objectContaining({ unitCode: "A-102", title: "Appartement A-102", description: "Deuxième étage", location: { country: "CI", city: "Abidjan", district: "Marcory", addressLine: "Zone 4, A-102" } })); });
  it("conserve les Buildings si la page suivante échoue", async () => { const client = fakeApi(); vi.mocked(client.listBuildings).mockResolvedValueOnce({ items: [building], pageInfo: { nextCursor: "opaque-building", hasNextPage: true } }).mockRejectedValueOnce(new Error("network")); show(client); await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(screen.getByRole("button", { name: "Afficher plus d’immeubles" })); expect(await screen.findByText(/Les immeubles déjà affichés restent disponibles/)).toBeVisible(); expect(screen.getByRole("group", { name: "Modifier Immeuble A" })).toBeVisible(); expect(client.listBuildings).toHaveBeenLastCalledWith(PROPERTY, "opaque-building"); });
  it("affiche un refus sans masquer les données chargées", async () => { const client = fakeApi(); vi.mocked(client.updateBuilding).mockRejectedValueOnce(new ApiForbiddenError()); show(client); const edit = await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(within(edit).getByRole("button", { name: "Enregistrer l’immeuble" })); await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("autorisation")); expect(edit).toBeVisible(); });
  it.each([
    [new ApiSessionExpiredError(), "session"],
    [new ApiProblem({ type: "conflict", title: "Conflit", status: 409, code: "PROPERTY_BUILDING_CODE_CONFLICT", correlationId: "correlation" }), "déjà utilisé"],
  ])("traduit les erreurs API de modification en français", async (failure, message) => { const client = fakeApi(); vi.mocked(client.updateBuilding).mockRejectedValueOnce(failure); show(client); const edit = await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(within(edit).getByRole("button", { name: "Enregistrer l’immeuble" })); await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent(message)); expect(edit).toBeVisible(); });
  it("actualise immédiatement le rôle après le premier immeuble", async () => { const client = fakeApi(); const roleChanged = vi.fn(); show(client, { ...property, structuralRole: "STANDALONE" }, roleChanged); await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.change(screen.getByLabelText("Code du nouvel immeuble"), { target: { value: "BAT-B" } }); fireEvent.change(screen.getByLabelText("Nom du nouvel immeuble"), { target: { value: "Immeuble B" } }); fireEvent.click(screen.getByRole("button", { name: "Ajouter l’immeuble" })); await screen.findByText(/Immeuble ajouté avec succès/); expect(roleChanged).toHaveBeenCalledWith("COMPOSITE"); });
  it("affiche les états vides Building et Unit", async () => { const client = fakeApi(); vi.mocked(client.listBuildings).mockResolvedValueOnce({ items: [], pageInfo: { nextCursor: null, hasNextPage: false } }); show(client); expect(await screen.findByText("Aucun immeuble n’est encore rattaché à ce bien.")).toBeVisible(); });
  it("affiche le résumé français d’une Unit et son état vide", async () => { const client = fakeApi(); show(client); await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(screen.getByRole("button", { name: "Afficher les unités" })); expect(await screen.findByRole("article", { name: "Unité A-101" })).toHaveTextContent("Appartement"); expect(screen.getByRole("article", { name: "Unité A-101" })).toHaveTextContent("Location longue durée"); expect(screen.getByRole("article", { name: "Unité A-101" })).toHaveTextContent("Rue 1, Cocody, Abidjan (CI)"); vi.mocked(client.listUnits).mockResolvedValueOnce({ items: [], pageInfo: { nextCursor: null, hasNextPage: false } }); fireEvent.click(screen.getByRole("button", { name: "Actualiser les unités" })); expect(await screen.findByText("Aucune unité dans cet immeuble.")).toBeVisible(); });
  it("propose une nouvelle tentative après une erreur initiale sans masquer la fiche", async () => { const client = fakeApi(); vi.mocked(client.listBuildings).mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce({ items: [building], pageInfo: { nextCursor: null, hasNextPage: false } }); show(client); const retry = await screen.findByRole("button", { name: "Réessayer de charger la composition" }); expect(screen.getByRole("alert")).toHaveTextContent("erreur inattendue"); fireEvent.click(retry); expect(await screen.findByRole("group", { name: "Modifier Immeuble A" })).toBeVisible(); });
  it("présente 401 et 404 locaux avec un retry conservant le Building", async () => { const sessionClient = fakeApi(); vi.mocked(sessionClient.listBuildings).mockRejectedValueOnce(new ApiSessionExpiredError()); const first = show(sessionClient); expect(await screen.findByRole("alert")).toHaveTextContent("session"); first.unmount(); const client = fakeApi(); vi.mocked(client.listUnits).mockRejectedValueOnce(new ApiProblem({ type: "not-found", title: "Introuvable", status: 404, code: "PROPERTY_UNIT_NOT_FOUND", correlationId: "correlation" })); show(client); const edit = await screen.findByRole("group", { name: "Modifier Immeuble A" }); fireEvent.click(screen.getByRole("button", { name: "Afficher les unités" })); expect(await screen.findByRole("alert")).toHaveTextContent("Cette unité est introuvable"); expect(screen.getByRole("button", { name: "Réessayer de charger les unités" })).toBeVisible(); expect(edit).toBeVisible(); });
});
