import { useEffect, useState } from "react";
import { Alert, Button, EmptyState, LoadingState, StatusBadge } from "../../ui/index.js";
import type { PropertyApplicationApi } from "./property-api.js";
import type { PropertyApplication, PropertyApplicationClientConversion, PropertyApplicationListItem, PropertyContract, PropertyViewingOutcomeStatus } from "./property-model.js";
import { applicationStatusLabel } from "./PropertyApplicationPanel.js";

export function PropertyApplicationsSection({propertyId,api}:Readonly<{propertyId:string;api:PropertyApplicationApi}>) {
  const [items,setItems]=useState<readonly PropertyApplicationListItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
  async function load(next?:string){setLoading(true);setError(false);try{const page=await api.listPropertyApplications(propertyId,next);if(!page||!Array.isArray(page.items)||!page.pageInfo)throw new Error("invalid response");setItems(old=>next?[...new Map([...old,...page.items].map(x=>[x.applicationId,x])).values()]:page.items);setCursor(page.pageInfo.nextCursor);}catch{setError(true);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[propertyId]);
  async function decide(item:PropertyApplicationListItem,kind:"approve"|"reject"|"withdraw"){setError(false);try{const changed=kind==="approve"?await api.approvePropertyApplication(propertyId,item.applicationId):kind==="reject"?await api.rejectPropertyApplication(propertyId,item.applicationId):await api.withdrawPropertyApplication(propertyId,item.applicationId);setItems(old=>old.map(x=>x.applicationId===changed.applicationId?{...x,...changed}:x));}catch{setError(true);}}
  return <section className="content-panel" id="property-applications"><div className="section-heading"><div><p className="eyebrow">Décision commerciale</p><h2>Candidatures</h2></div></div>{error&&<Alert tone="danger" title="Impossible de traiter les candidatures"><p>Les candidatures déjà affichées restent disponibles.</p></Alert>}{loading&&items.length===0?<LoadingState label="Chargement des candidatures…"/>:items.length===0&&!error?<EmptyState title="Aucune candidature" description="Les candidatures créées après une visite positive apparaîtront ici."/>:<ul className="inquiry-list application-list">{items.map(x=><li key={x.applicationId}><div className="application-summary"><div><p className="eyebrow">Candidat</p><h3>{x.candidate.contactName}</h3>{x.candidate.phoneNumber&&<p><span className="visually-hidden">Téléphone : </span><a href={`tel:${x.candidate.phoneNumber}`}>{x.candidate.phoneNumber}</a></p>}{x.candidate.email&&<p><span className="visually-hidden">Email : </span><a href={`mailto:${x.candidate.email}`}>{x.candidate.email}</a></p>}</div><div><h4>Visite</h4><p>{formatDate(x.viewing.startsAt,x.viewing.timeZone)}</p><p>{outcomeLabel(x.outcome.status)}</p></div><div><h4>Candidature soumise le</h4><p>{formatDate(x.createdAt,x.viewing.timeZone)}</p></div></div><div><StatusBadge>{applicationStatusLabel(x.status)}</StatusBadge>{x.status==="SUBMITTED"&&<div className="viewing-actions"><Button onClick={()=>void decide(x,"approve")}>Approuver</Button><Button variant="secondary" onClick={()=>void decide(x,"reject")}>Rejeter</Button><Button variant="secondary" onClick={()=>void decide(x,"withdraw")}>Retirer</Button></div>}{x.status==="APPROVED"&&<ApplicationClient propertyId={propertyId} applicationId={x.applicationId} api={api}/>}</div></li>)}</ul>}{cursor&&<Button loading={loading} onClick={()=>void load(cursor)}>Afficher plus</Button>}</section>;
}

function formatDate(value:string,timeZone:string){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"long",timeStyle:"short",timeZone}).format(new Date(value));}
function outcomeLabel(status:PropertyViewingOutcomeStatus){return status==="PROCEED"?"Suite favorable":status==="DECLINED"?"Suite défavorable":"Suivi nécessaire";}

function ApplicationClient({propertyId,applicationId,api}:Readonly<{propertyId:string;applicationId:string;api:PropertyApplicationApi}>) {
  const [conversion,setConversion]=useState<PropertyApplicationClientConversion>(),[contract,setContract]=useState<PropertyContract>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);const retrieve=api.retrievePropertyApplicationClient;if(!retrieve){setLoading(false);return()=>{active=false;};}retrieve(propertyId,applicationId).then(value=>{if(active)setConversion(value);}).catch(()=>undefined).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[api,propertyId,applicationId]);
  async function convert(){const execute=api.convertPropertyApplicationToClient;if(!execute)return;setBusy(true);setError(false);try{setConversion(await execute(propertyId,applicationId));}catch{setError(true);}finally{setBusy(false);}}
  if(loading)return <p>Vérification du client…</p>;
  async function createContract(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const execute=api.createPropertyContractFromApplication;if(!execute)return;setBusy(true);setError(false);const data=new FormData(event.currentTarget);try{setContract(await execute(propertyId,applicationId,{reference:String(data.get("reference")??""),...(data.get("startDate")?{startDate:String(data.get("startDate"))}:{}),...(data.get("endDate")?{endDate:String(data.get("endDate"))}:{}),...(data.get("notes")?{notes:String(data.get("notes"))}:{})}));}catch{setError(true);}finally{setBusy(false);}}
  if(conversion)return <div><p>Convertie en client</p><strong>{conversion.client.displayName}</strong>{conversion.client.email&&<p>{conversion.client.email}</p>}{contract?<div><p>Contrat brouillon</p><strong>{contract.reference}</strong><p>Activez le contrat séparément dans la section Clients et contrats.</p></div>:<form className="compact-form" onSubmit={createContract}><h4>Créer le contrat</h4><p>Client : {conversion.client.displayName}</p><p>Type : Bail longue durée</p><label>Référence<input name="reference" required maxLength={100}/></label><label>Date de début<input name="startDate" type="date"/></label><label>Date de fin<input name="endDate" type="date"/></label><label>Note<textarea name="notes" maxLength={5000}/></label>{error&&<Alert tone="danger" title="Impossible de créer le contrat"><p>Vérifiez les informations, vos autorisations ou l’éligibilité du bien.</p></Alert>}<Button type="submit" loading={busy}>Créer le contrat</Button></form>}</div>;
  return <div>{error&&<Alert tone="danger" title="Impossible de créer le client"><p>Vérifiez vos autorisations ou réessayez.</p></Alert>}<Button loading={busy} onClick={()=>void convert()}>Créer le client</Button><p>Le contrat sera créé séparément.</p></div>;
}
