import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router";
import type { PropertyApi } from "./property-api.js";
import { toPropertyUiError, type PropertyUiError } from "./property-errors.js";
import type { Property, PropertyBuilding, PropertyUnit } from "./property-model.js";

const CODE_PATTERN = "[A-Za-z0-9][A-Za-z0-9._/ \\-]{0,49}";
interface UnitState { readonly items: readonly PropertyUnit[]; readonly nextCursor: string | null; readonly hasNextPage: boolean; readonly loading: boolean; readonly error?: PropertyUiError; }
const emptyUnits: UnitState = { items: [], nextCursor: null, hasNextPage: false, loading: false };

export function PropertyCompositionSection({ property, api }: Readonly<{ property: Property; api: PropertyApi }>) {
  const [buildings, setBuildings] = useState<readonly PropertyBuilding[]>([]); const [buildingCursor, setBuildingCursor] = useState<string | null>(null); const [hasMoreBuildings, setHasMoreBuildings] = useState(false);
  const [units, setUnits] = useState<Record<string, UnitState>>({}); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [busyKey, setBusyKey] = useState<string>();
  const [message, setMessage] = useState<string>(); const [error, setError] = useState<PropertyUiError>(); const [pageError, setPageError] = useState<string>();
  useEffect(() => { let active = true; if (property.structuralRole === "UNIT") { setLoading(false); return; } setLoading(true); setError(undefined); void api.listBuildings(property.propertyId).then((page) => { if (!active) return; setBuildings(Array.isArray(page.items) ? page.items : []); setBuildingCursor(page.pageInfo?.nextCursor ?? null); setHasMoreBuildings(page.pageInfo?.hasNextPage ?? false); }).catch((caught) => { if (active) setError(toPropertyUiError(caught)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [api, property.propertyId, property.structuralRole]);
  function clearFeedback() { setMessage(undefined); setError(undefined); }
  async function addBuilding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setBusyKey("create-building"); clearFeedback(); const data = new FormData(form); try { const building = await api.createBuilding(property.propertyId, { buildingCode: String(data.get("buildingCode")), name: String(data.get("name")) }); setBuildings((current) => sortBuildings(uniqueBuildings([...current, building]))); form.reset(); setMessage("Immeuble ajouté avec succès."); } catch (caught) { setError(toPropertyUiError(caught)); } finally { setBusyKey(undefined); } }
  async function updateBuilding(event: FormEvent<HTMLFormElement>, buildingId: string) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusyKey(`building-${buildingId}`); clearFeedback(); try { const updated = await api.updateBuilding(property.propertyId, buildingId, { buildingCode: String(data.get("buildingCode")), name: String(data.get("name")) }); setBuildings((current) => sortBuildings(current.map((item) => item.buildingId === buildingId ? updated : item))); setMessage("Immeuble modifié avec succès."); } catch (caught) { setError(toPropertyUiError(caught)); } finally { setBusyKey(undefined); } }
  async function loadMoreBuildings() { if (!buildingCursor || loadingMore) return; setLoadingMore(true); setPageError(undefined); try { const page = await api.listBuildings(property.propertyId, buildingCursor); setBuildings((current) => sortBuildings(uniqueBuildings([...current, ...page.items]))); setBuildingCursor(page.pageInfo.nextCursor); setHasMoreBuildings(page.pageInfo.hasNextPage); } catch (caught) { setPageError(`${toPropertyUiError(caught).message} Les immeubles déjà affichés restent disponibles.`); } finally { setLoadingMore(false); } }
  async function loadUnits(buildingId: string, cursor?: string) { setUnits((current) => ({ ...current, [buildingId]: { ...(current[buildingId] ?? emptyUnits), loading: true, error: undefined } })); try { const page = await api.listUnits(property.propertyId, buildingId, cursor); setUnits((current) => { const previous = cursor ? current[buildingId]?.items ?? [] : []; return { ...current, [buildingId]: { items: sortUnits(uniqueUnits([...previous, ...page.items])), nextCursor: page.pageInfo.nextCursor, hasNextPage: page.pageInfo.hasNextPage, loading: false } }; }); } catch (caught) { setUnits((current) => ({ ...current, [buildingId]: { ...(current[buildingId] ?? emptyUnits), loading: false, error: toPropertyUiError(caught) } })); } }
  async function addUnit(event: FormEvent<HTMLFormElement>, buildingId: string) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusyKey(`create-unit-${buildingId}`); clearFeedback(); try { const unit = await api.createUnit(property.propertyId, buildingId, { unitCode: String(data.get("unitCode")), title: String(data.get("title")), propertyType: String(data.get("propertyType")) as Property["propertyType"], transactionType: String(data.get("transactionType")) as Property["transactionType"], location: property.location }); setUnits((current) => ({ ...current, [buildingId]: { ...(current[buildingId] ?? emptyUnits), items: sortUnits(uniqueUnits([...(current[buildingId]?.items ?? []), unit])) } })); form.reset(); setMessage("Unité ajoutée avec succès."); } catch (caught) { setError(toPropertyUiError(caught)); } finally { setBusyKey(undefined); } }
  async function updateUnit(event: FormEvent<HTMLFormElement>, buildingId: string, unitPropertyId: string) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusyKey(`unit-${unitPropertyId}`); clearFeedback(); try { const updated = await api.updateUnitCode(property.propertyId, buildingId, unitPropertyId, String(data.get("unitCode"))); setUnits((current) => ({ ...current, [buildingId]: { ...(current[buildingId] ?? emptyUnits), items: sortUnits((current[buildingId]?.items ?? []).map((item) => item.property.propertyId === unitPropertyId ? updated : item)) } })); setMessage("Code de l’unité modifié avec succès."); } catch (caught) { setError(toPropertyUiError(caught)); } finally { setBusyKey(undefined); } }
  if (property.structuralRole === "UNIT") return null;
  return <section className="content-panel" aria-labelledby="composition-title" aria-busy={loading || loadingMore || busyKey !== undefined}><div className="section-heading"><div><p className="eyebrow">Organisation</p><h2 id="composition-title">Composition du bien</h2></div></div>
    {message && <div className="form-message is-success" role="status">{message}</div>}{error && <div className="form-message" role="alert">{error.message}</div>}{loading ? <p role="status">Chargement de la composition…</p> : <>
      <form onSubmit={addBuilding}><fieldset disabled={busyKey !== undefined}><legend>Ajouter un immeuble</legend><CodeField name="buildingCode" label="Code du nouvel immeuble" /><label>Nom du nouvel immeuble<input name="name" required maxLength={200} /></label><button className="primary-action" type="submit">Ajouter l’immeuble</button></fieldset></form>
      {buildings.length === 0 ? <p>Aucun immeuble pour ce bien.</p> : <ul className="composition-list">{buildings.map((building) => <li key={building.buildingId}><form onSubmit={(event) => void updateBuilding(event, building.buildingId)}><fieldset disabled={busyKey !== undefined}><legend>Modifier {building.name}</legend><CodeField name="buildingCode" label={`Code de ${building.name}`} defaultValue={building.buildingCode} /><label>Nom de l’immeuble<input name="name" required maxLength={200} defaultValue={building.name} /></label><button className="secondary-action" type="submit">Enregistrer l’immeuble</button></fieldset></form>
        <button type="button" className="secondary-action" onClick={() => void loadUnits(building.buildingId)} disabled={units[building.buildingId]?.loading}>{units[building.buildingId]?.loading ? "Chargement…" : "Afficher les unités"}</button>
        <form onSubmit={(event) => void addUnit(event, building.buildingId)}><fieldset disabled={busyKey !== undefined}><legend>Ajouter une unité à {building.name}</legend><CodeField name="unitCode" label="Code de la nouvelle unité" /><label>Titre de l’unité<input name="title" required maxLength={200} /></label><label>Type<select name="propertyType"><option value="APARTMENT">Appartement</option><option value="HOUSE">Maison</option><option value="LAND">Terrain</option><option value="COMMERCIAL">Local commercial</option><option value="OTHER">Autre</option></select></label><label>Projet<select name="transactionType"><option value="LONG_TERM_RENTAL">Location longue durée</option><option value="SHORT_TERM_RENTAL">Location courte durée</option><option value="SALE">Vente</option></select></label><button type="submit" className="primary-action">Ajouter l’unité</button></fieldset></form>
        {units[building.buildingId]?.error && <div className="form-message" role="alert">{units[building.buildingId]?.error?.message} Les unités déjà affichées restent disponibles.</div>}<ul>{(units[building.buildingId]?.items ?? []).map((unit) => <li key={unit.property.propertyId}><form onSubmit={(event) => void updateUnit(event, building.buildingId, unit.property.propertyId)}><fieldset disabled={busyKey !== undefined}><legend>Modifier le code de {unit.property.title}</legend><CodeField name="unitCode" label={`Code de ${unit.property.title}`} defaultValue={unit.unitCode} /><button className="secondary-action" type="submit">Enregistrer le code</button> <Link to={`/properties/${unit.property.propertyId}`}>Ouvrir la fiche</Link></fieldset></form></li>)}</ul>
        {units[building.buildingId]?.hasNextPage && <button type="button" className="secondary-action" disabled={units[building.buildingId]?.loading} onClick={() => void loadUnits(building.buildingId, units[building.buildingId]?.nextCursor ?? undefined)}>Afficher plus d’unités</button>}</li>)}</ul>}
      {pageError && <div className="form-message" role="alert">{pageError}</div>}{hasMoreBuildings && <button type="button" className="secondary-action" disabled={loadingMore} onClick={() => void loadMoreBuildings()}>{loadingMore ? "Chargement…" : "Afficher plus d’immeubles"}</button>}
    </>}</section>;
}
function CodeField({ name, label, defaultValue }: Readonly<{ name: string; label: string; defaultValue?: string }>) { return <label>{label}<input name={name} required minLength={1} maxLength={50} pattern={CODE_PATTERN} title="Utilisez des lettres, chiffres, espaces, points, tirets, barres obliques ou caractères de soulignement." defaultValue={defaultValue} /></label>; }
function uniqueBuildings(items: readonly PropertyBuilding[]) { return [...new Map(items.map((item) => [item.buildingId, item])).values()]; }
function uniqueUnits(items: readonly PropertyUnit[]) { return [...new Map(items.map((item) => [item.property.propertyId, item])).values()]; }
function sortBuildings(items: readonly PropertyBuilding[]) { return [...items].sort((a, b) => a.buildingCode.localeCompare(b.buildingCode) || a.buildingId.localeCompare(b.buildingId)); }
function sortUnits(items: readonly PropertyUnit[]) { return [...items].sort((a, b) => a.unitCode.localeCompare(b.unitCode) || a.property.propertyId.localeCompare(b.property.propertyId)); }
