import { InvalidPropertyInquiryInputError, PropertyInquiry, type PropertyInquiryStatus, type PropertyInquiryIntent, type PropertyInquiryPreferredContactChannel } from "../domain/property-inquiry.js";
import { authorizedTenant, type PropertyAuthority } from "./property-authority.js";
import type { PropertyInquiryCursor, PropertyInquiryPage, PropertyInquiryRepository } from "./property-inquiry-repository.js";
export class PropertyInquiryNotFoundError extends Error { readonly code="PROPERTY_INQUIRY_NOT_FOUND"; }
export class InvalidPropertyInquiryListError extends Error { readonly code="INVALID_PROPERTY_INQUIRY_LIST"; }
export class SubmitPublicPropertyInquiry {
  constructor(private readonly repository:PropertyInquiryRepository,private readonly ids:{generate():string},private readonly clock:{now():string}){}
  async execute(command:Readonly<{tenantId:string;publicPropertyId:string;contactName:string;email?:string;phoneNumber?:string;message?:string;intent:PropertyInquiryIntent;preferredContactChannel?:PropertyInquiryPreferredContactChannel;consent:boolean;consentVersion:string;idempotencyKey:string;correlationId:string}>):Promise<{inquiryId:string;receivedAt:string}>{
    if(!command.consent)throw new InvalidPropertyInquiryInputError("consent"); const now=this.clock.now();
    const inquiry=PropertyInquiry.create({inquiryId:this.ids.generate(),tenantId:command.tenantId,propertyId:command.publicPropertyId,contactName:command.contactName,...(command.email===undefined?{}:{email:command.email}),...(command.phoneNumber===undefined?{}:{phoneNumber:command.phoneNumber}),...(command.message===undefined?{}:{message:command.message}),intent:command.intent,...(command.preferredContactChannel===undefined?{}:{preferredContactChannel:command.preferredContactChannel}),consentVersion:command.consentVersion,consentGivenAt:now,idempotencyKey:command.idempotencyKey,createdAt:now,updatedAt:now});
    const saved=await this.repository.submitForPublishedProperty(inquiry,command.publicPropertyId,{correlationId:command.correlationId,actorId:"public-inquiry"}); if(saved===undefined)throw new PropertyInquiryNotFoundError(); return{inquiryId:saved.values.inquiryId,receivedAt:saved.values.createdAt};
  }
}
export class ListPropertyInquiries { constructor(private readonly repository:PropertyInquiryRepository){} async execute(q:Readonly<{authority:PropertyAuthority;propertyId:string;limit?:number;cursor?:PropertyInquiryCursor;status?:PropertyInquiryStatus}>):Promise<PropertyInquiryPage>{const limit=q.limit??20;if(!Number.isInteger(limit)||limit<1||limit>100)throw new InvalidPropertyInquiryListError();const page=await this.repository.list(authorizedTenant(q.authority,"LIST_PROPERTY_INQUIRIES"),q.propertyId,limit,q.cursor,q.status);if(!page)throw new PropertyInquiryNotFoundError();return page;} }
export class RetrievePropertyInquiry {constructor(private readonly repository:PropertyInquiryRepository){}async execute(q:Readonly<{authority:PropertyAuthority;propertyId:string;inquiryId:string}>){const item=await this.repository.find(authorizedTenant(q.authority,"RETRIEVE_PROPERTY_INQUIRY"),q.propertyId,q.inquiryId);if(!item)throw new PropertyInquiryNotFoundError();return item;}}
abstract class TransitionInquiry {constructor(private readonly repository:PropertyInquiryRepository,private readonly clock:{now():string},private readonly transition:"acknowledge"|"close"){}async execute(c:Readonly<{authority:PropertyAuthority;propertyId:string;inquiryId:string;correlationId:string}>){const tenant=authorizedTenant(c.authority,"MANAGE_PROPERTY_INQUIRIES");const now=this.clock.now();const item=await this.repository.update(tenant,c.propertyId,c.inquiryId,(i)=>this.transition==="acknowledge"?i.acknowledge(now):i.close(now),{actorId:c.authority.actorId,correlationId:c.correlationId});if(!item)throw new PropertyInquiryNotFoundError();return item;}}
export class AcknowledgePropertyInquiry extends TransitionInquiry {constructor(r:PropertyInquiryRepository,c:{now():string}){super(r,c,"acknowledge");}}
export class ClosePropertyInquiry extends TransitionInquiry {constructor(r:PropertyInquiryRepository,c:{now():string}){super(r,c,"close");}}
