export type PropertyGrant = "CREATE_PROPERTY" | "RETRIEVE_PROPERTY" | "LIST_PROPERTIES" | "UPDATE_PROPERTY_DETAILS" | "UPDATE_PROPERTY_CORE_INFORMATION"
  | "UPDATE_PROPERTY_PRICING"
  | "CREATE_PROPERTY_OWNER" | "RETRIEVE_PROPERTY_OWNER" | "LIST_PROPERTY_OWNERS" | "UPDATE_PROPERTY_OWNER"
  | "ASSIGN_PROPERTY_OWNER" | "RETRIEVE_PROPERTY_OWNERSHIP" | "REMOVE_PROPERTY_OWNER"
  | "CREATE_PROPERTY_BUILDING" | "RETRIEVE_PROPERTY_COMPOSITION" | "UPDATE_PROPERTY_BUILDING"
  | "CREATE_PROPERTY_UNIT" | "UPDATE_PROPERTY_UNIT_STRUCTURE" | "PUBLISH_PROPERTY" | "WITHDRAW_PROPERTY_FROM_CATALOG"
  | "RETRIEVE_PROPERTY_AVAILABILITY" | "UPDATE_PROPERTY_AVAILABILITY"
  | "RETRIEVE_PROPERTY_GEOLOCATION" | "UPDATE_PROPERTY_GEOLOCATION" | "REMOVE_PROPERTY_GEOLOCATION"
  | "CREATE_PROPERTY_PHOTO" | "RETRIEVE_PROPERTY_PHOTOS" | "SELECT_PROPERTY_PRIMARY_PHOTO" | "DELETE_PROPERTY_PHOTO" | "REORDER_PROPERTY_PHOTOS"
  | "RETRIEVE_PROPERTY_PHOTO_STANDARD" | "MANAGE_PROPERTY_PHOTO_STANDARD"
  | "RETRIEVE_PROPERTY_WORKSPACE"
  | "RETRIEVE_PROPERTY_AMENITIES" | "UPDATE_PROPERTY_AMENITIES"
  | "LIST_PROPERTY_INQUIRIES" | "RETRIEVE_PROPERTY_INQUIRY" | "MANAGE_PROPERTY_INQUIRIES"
  | "RETRIEVE_PROPERTY_VIEWINGS" | "MANAGE_PROPERTY_VIEWINGS"
  | "RETRIEVE_PROPERTY_VIEWING_OUTCOMES" | "MANAGE_PROPERTY_VIEWING_OUTCOMES"
  | "RETRIEVE_PROPERTY_APPLICATIONS" | "MANAGE_PROPERTY_APPLICATIONS"
  | "CREATE_PROPERTY_CLIENT" | "RETRIEVE_PROPERTY_CLIENTS"
  | "CREATE_PROPERTY_CONTRACT" | "RETRIEVE_PROPERTY_CONTRACTS" | "UPDATE_PROPERTY_CONTRACT"
  | "MANAGE_PROPERTY_CONTRACT_LIFECYCLE";

export interface PropertyAuthority {
  readonly actorId: string;
  readonly authorityId: string;
  readonly grants: readonly PropertyGrant[];
  readonly tenantIds: readonly string[];
}

export class PropertyForbiddenError extends Error { readonly code = "PROPERTY_FORBIDDEN"; }

export function authorizedTenant(authority: PropertyAuthority, grant: PropertyGrant): string {
  if (!authority.grants.includes(grant) || authority.tenantIds.length !== 1) throw new PropertyForbiddenError();
  return authority.tenantIds[0]!;
}
